import  './applicationStructure.cy'
import './authenticationProcess.cy'
import './applicationStructure.cy'
import './userCanToggleApplicationLanguage.cy'
import './dashboardViewForVendors.cy'
import './venueSetup.cy'
import './venueEdit.cy'